### ISSUE TITLE
Panavia Tornado avión de combate

### ISSUE THREAD

**Issue by bforteza** [oscarperpinan/prueba2_0303#6]
El Panavia Tornado es un [avión de combate](https://es.wikipedia.org/wiki/Avi%C3%B3n_de_combate) bimotor con [ala de geometría variable](https://es.wikipedia.org/wiki/Ala_de_geometr%C3%ADa_variable) que fue desarrollado conjuntamente por [Reino Unido](https://es.wikipedia.org/wiki/Reino_Unido), [Alemania Occidental](https://es.wikipedia.org/wiki/Alemania_Occidental) e [Italia](https://es.wikipedia.org/wiki/Italia) en los [años 1970](https://es.wikipedia.org/wiki/A%C3%B1os_1970). Se crearon tres versiones principales de este avión: el [cazabombardero](https://es.wikipedia.org/wiki/Cazabombardero) Tornado IDS, el avión de [supresión de defensas aéreas enemigas](https://es.wikipedia.org/wiki/Supresi%C3%B3n_de_defensas_a%C3%A9reas_enemigas) Tornado ECR y el [interceptor](https://es.wikipedia.org/wiki/Interceptor) [Tornado ADV](https://es.wikipedia.org/wiki/Tornado_ADV).

**Comment by oscarperpinan** [comment]
Gracias por la información.
